### ISSUE TITLE
SQL error after plugin installation

### ISSUE THREAD

**Issue by Victor-IT** [manelperez/kanboard-plugin-voting#1]
After plugin installation and trying to create new task or save/edit early created:

`Internal Error: SQL Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'points' in 'field list'`

_PHP: 7.1.9
KB: 1.2.5
SQL: 5.6.39-83.1_

**Comment by manelperez** [comment]
Incorrect column name. 
The column name has been changed.
