### ISSUE TITLE
error message on pending voting view

### ISSUE THREAD

**Issue by achmarah** [manelperez/kanboard-plugin-voting#2]
After I install the plugin, I went to my dashboard and click the pending voting link, the following error message displayed. Any database adjustment needed to run the plugin?

![image](https://user-images.githubusercontent.com/40012864/43385823-fac1fea6-940b-11e8-8fb9-02f7c835f107.png)

**Comment by manelperez** [comment]
It does not seem to be a database error.
Possibly it has to do with the group to which the user belongs (Users must belong to a group).
