### ISSUE TITLE
Database error upon creating task

### ISSUE THREAD

**Issue by Skyridr** [manelperez/kanboard-plugin-voting#3]
I've installed this plugin through kanboard admin control panel (plugin section), and once I create a new task and submit it, getting the following error:

"Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 no such table: voting"

Doesn't appear that the table is being added/created after you install the plugin.  Using SQLite btw.

**Comment by manelperez** [comment]
There isn't schema definition for SQLite. Currently, the table definition is for MySQL. 
You can see [https://github.com/manelperez/kanboard-plugin-voting/blob/master/Schema](url)

It would be necessary a development for SQLite .
